# vim: ts=4 sw=4 et
imports:
    - 'cloudify.types'
    - 'neutron-sg-type.yaml'


blueprint:
    name: 'neutron-security_group-test'
    topology:
        -
            name: 'neutron_security_group'
            type: 'neutron_security_group'
            interfaces:
                    - 'cloudify.interfaces.security_group_provisioner'
            properties:
                security_group:
                    name: 'neutron_security_group_test'
                    description: 'Neutron security group test'
                    # disable_egress: true
                    rules:
                        -
                            remote_ip_prefix: 1.2.3.0/24
                        -
                            port: 80
                        -
                            remote_ip_prefix: 2.3.4.0/24
                            port_range_min: 65500
                            port_range_max: 65510
                        -
                            remote_group_name: default
                            port: 65520
                        -
                            direction: egress
                            remote_ip_prefix: 3.4.5.0/24
                            port: 443


            policies:
                -
                    name: 'start_detection_policy'
                    rules:
                        -
                            type: 'state_equals'
                            properties:
                                service: 'security group status'
                                state: 'running'
